services:
  scraper:
    build: packages/scraper
    ports:
      - "8090:8080"
    volumes:
      - ./packages/scraper/userdata:/userdata
    environment:
      - CAMOUFOX_HEADLESS=virtual
      - CAMOUFOX_PERSISTENT=true

  processor:
    build:
      context: .
      dockerfile: packages/processor/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SCRAPER_URL=http://scraper:8080
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_AI_MODEL=milkey/reader-lm-v2:latest
    depends_on:
      - scraper
